#!/usr/bin/env bash
set -euo pipefail

SCRIPT_PATH=$(realpath "${BASH_SOURCE[0]}")
DOT_DIR=$(cd "$(dirname "$SCRIPT_PATH")/../.." && pwd)
SECRETS_HELPER="$DOT_DIR/custom_bins/dotfiles-secrets"

# Hooks run with minimal PATH — ensure bws/sops are discoverable
for d in "$HOME/.local/bin" /opt/homebrew/bin /usr/local/bin "$DOT_DIR/custom_bins"; do
  [[ -d "$d" ]] && [[ ":$PATH:" != *":$d:"* ]] && PATH="$d:$PATH"
done
export PATH

# Two things this must NOT do, both of which it used to do:
#   - silence the helper's stderr. Its diagnostics (ambiguous env name, stale
#     cache, missing BWS token) are the only signal that injection failed.
#   - treat exit 0 as success on its own. The helper can exit 0 having resolved
#     nothing, and then the wrapped command runs keyless — which is how the
#     auto-classifier failed open for ~349 denials without a single error.
# Still exec unconditionally: the wrapped command (usually the classifier) has
# its own no-key handling, and exiting non-zero here would replace a precise
# stderr message with a generic hook failure.
if [[ -z "${ANTHROPIC_API_KEY:-}" && -x "$SECRETS_HELPER" ]]; then
  if exports=$("$SECRETS_HELPER" shell ANTHROPIC_API_KEY) && [[ -n "$exports" ]]; then
    # Safe here: output is generated by our own helper with shell escaping.
    eval "$exports"
  else
    echo "with-anthropic-key.sh: could not resolve ANTHROPIC_API_KEY (see above); running without it." >&2
  fi
fi

exec "$@"
